### ISSUE TITLE
Text Hook for 1.2 JPN

### ISSUE THREAD

**Issue by terry1994** [glankk/gz#2]
I am trying to port the text hook 1.2. I have found what I believe are the equivalent addresses. To be truthfully honest, I don't actually know quite what I am looking for. I have instead located addresses which are representative of the addresses that your text hook contains. 

They are as follows:
```
8005248B 0001
8105237E 0000
8105237C 0000
810523DC 0C18
810523DE 0000
```

A crash occurs when enabling these hooks and subsequently loading the lua patch. I am experimenting with a simple Hello world for the time being until I am able to actually get that working, I won't begin on the other stuff. Do you have any pointers or tips for how to address this? Thanks!

**Comment by glankk** [comment]
There are three functions used for putting text on the screen; SetTextRGBA, SetTextXY, and SetTextString.
Their addresses will most likely be different on 1.2 than 1.0, so you will first need to locate them. Their addresses have been documented for 1.0, but i don't know about 1.2. You might have to find them yourself. There is also another problem; the first argument to all of these functions is a pointer to some sort of data structure, whose layout, as far as i know, is unknown. The workaround for this is to find a point in the game's code that calls these functions, replace them with a call to our own hook function (specifically, SetTextString is being hooked by text_hook), and then pass the argument that was given to our own function on to the game's text functions. These lines:
```
81051D4C 0C18
81051D4E 0000
```
are what replaces the SetTextString call with a call to our own `_start` function.
However, there is yet another problem. The function that contains the call to SetTextString is never actually called by the game, because that call is being branched over by the game's code, presumably due to some debugging setting being turned off. The first three lines are there to replace these branch instructions with code that will make the control flow reach our hook function with the data structure pointer argument. This means that in addition to finding the text function addresses, you will also need to find the SetTextString call, and the branch instructions that prevent the control flow from reaching that call. These addresses will also most likely be different on 1.2 than 1.0, though it's possible they all just have a constant offset from the 1.0 addresses.

Some disassembly will surely be needed for this task. For that I recommend Nemu64, as it has the richest set of debugging tools out of all n64 emulators.

**Comment by terry1994** [comment]
Good news! As it turns out the GameShark codes I ported were in fact correct. I had a feeling they were as I was able to cause the game to freeze by calling exit(0) in the script, giving me the idea that the injected code was in fact being accessed. I didn't port the text functions which were using the addresses of the 1.0 ROM and that was causing a freeze.

I have since ported the SetText functions to 1.2 and submitted a PR to your n64 toolchain, only having modified z64.h and extended the preprocessor pattern to accomodate. I am able to achieve a hello world without issue now. There are some obvious issues like the huge number of memory addresses that need porting but that hopefully won't be a huge drama.
