### ISSUE TITLE
Practice for 1.1 exlusive tricks

### ISSUE THREAD

**Issue by SlaskPrask** [glankk/gz#4]
Are you planning to port the codes to 1.1 in the near future? there is one trick which is 1.1 exclusive that really is annoying to practice on the real cart and it includes bomb oi.

**Comment by glankk** [comment]
Though there will probably be a 1.1 port eventually, there are no plans of one at the moment. It should be a while before one is available, unless someone volunteers to make one.

**Comment by terry1994** [comment]
I have got it working on 1.2 without issue and am working on altering the entire project to support multiple versions. So a 1.1 port shouldn't be out of the question, although I do not have much interest in doing it.

I have a spreadsheet of 1.0/1.2 addresses and there are some fairly clear patterns in a large portion of the addresses. However, some require additional work, in which case you basically have three options:

1. **Reverse engineering** (Can be difficult and time consuming. Requires Nemu64 and some MIPS knowledge).
2. **Memory viewing/monitoring** (Easy but time consuming. MHS or Cheat Engine).
3. **RAM dump comparison** (Easy and relatively quick).
4. **Gameshark code porting** (Easy but limited).

Most of the addresses I located were done via RAM dump comparison and by porting GS codes. The issue with GS codes is that not everything in gz has a GS code. Comparing RAM dumps is easy, simply load the 1.0 ROM in an emulator. Start a game, exit the house and re-enter without touching anything at all. Do the same in the 1.1 ROM. Now, you'll have two RAM dumps with a **lot** in common, the issue is that many things will be offset. You'll work out a pattern, however, don't gamble on it, check all addresses manually, unless for example. you are working with game items/weapons, you can safely assume the offset is constant - it was between 1.0 and 1.2. I doubt 1.1 will have any intermediate changes introduced. 1.1 also has more codes available than 1.2, so you may have better luck than I did.

**Comment by glankk** [comment]
Support for 1.1 has now been implemented and will be available with the next release.
